// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "hcm": Application User Types
//
// Command:
// $ goagen
// --design=github.com/minhkhiemm/hcm/design
// --out=$(GOPATH)/src/github.com/minhkhiemm/hcm
// --version=v1.3.1

package app
